# 5 pandas入門

## 5.1 pandasのデータ構造

### 5.1.1 シリーズ（Series）

In [148]:
import pandas as pd

obj=pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [149]:
obj.values

array([ 4,  7, -5,  3])

In [150]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [151]:
obj2=pd.Series([4,7,-5,3],index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [152]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [153]:
obj2['a']

-5

In [154]:
obj2['d']=6
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [155]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [156]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [157]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [158]:
import numpy as np

np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [159]:
'b' in obj2

True

In [160]:
'e' in obj2

False

In [161]:
#ディクショナリを使ってシリーズを作成することができる
sdata={'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}
obj3=pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [162]:
states=['California','Ohio','Oregon','Texas']
obj4=pd.Series(sdata,index=states)  #キーの順番は上書きすることができる
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [163]:
pd.isnull(obj4) #欠損値があればTrueを返す

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [164]:
pd.notnull(obj4)    #欠損値があればFalseを返す

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [165]:
obj4.isnull()   #インスタンスメソッドとしても持っている

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [166]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [167]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [168]:
obj3+obj4   #別々にインデックス付けされたデータが自動的に整形される

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [169]:
obj4.name='population'
obj4.index.name='state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [170]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [171]:
obj.index=['Bob','Steve','Jeff','Ryan'] #シリーズのインデックスは代入して置き換えることができる
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### 5.1.2 データフレーム（DataFrame）

In [172]:
data={'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada',],
      'year':[2000,2001,2002,2001,2002,2003,],
      'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame=pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [173]:
frame.head()    #最初の5行だけ抽出する

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [174]:
pd.DataFrame(data,columns=['year','state','pop'])   #列の順番を指定する

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [175]:
frame2=pd.DataFrame(data,columns=['year','state','pop','debt'],
             index=['one','two','three','four','five','six'])   #列がデータを持っていない場合は欠損値が代入される
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [176]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [177]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [178]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [179]:
frame2.loc['three'] #名前で参照するときはlocという属性を使う

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [180]:
frame2['debt']=16.5 #列の値は代入して変更できる
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [181]:
frame2['debt']=np.arange(6.)    #配列を代入することもできる
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [182]:
val=pd.Series([-1.2,-1.5,-1.7],index=['two','four','five']) #シリーズを列に代入する
frame2['debt']=val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [183]:
frame2['eastern']=frame2.state=='Ohio'  #存在しない列に代入を行うと、新しい列が作成される
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [184]:
del frame2['eastern']   #列を削除するにはdelキーワードを使う
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

* データフレームをインデックスで参照して取得できる列は、データフレームの内部に持っているデータへの参照ビューであり、コピーではない
* 取得したシリーズに対して置き換えなどの変更を行うと、データフレームにも反映される
* 列は明示的にシリーズのcopyメソッドを使うとコピーを取得することができる

In [185]:
pop={'Nevada':{2001:2.4,2002:2.9},
     'Ohio':{2000:1.5,2001:1.7,2002:3.6}}   #ネストしたディクショナリをデータフレームに渡すと、外側のキーを列のインデックス、内側のキーを行のインデックスとして解釈する
frame3=pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [186]:
frame3.T    #行と列を転置

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [187]:
pd.DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [188]:
pdata={'Ohio':frame3['Ohio'][:-1],
       'Nevada':frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [189]:
frame3['Ohio'][:-1]

2001    1.7
2002    3.6
Name: Ohio, dtype: float64

In [190]:
frame3['Nevada'][:2]

2001    2.4
2002    2.9
Name: Nevada, dtype: float64

In [191]:
frame3.index.name='year';frame3.columns.name='state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [192]:
frame3.values   #values属性を参照すると、データフレームの中のデータが2次元のndarrayとして返される

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [193]:
frame2.values   #データフレームの列が異なるdtypeを持つ場合は、全ての列に対応したdtypeが使われる

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### 5.1.3 インデックスオブジェクト

In [194]:
obj=pd.Series(range(3),index=['a','b','c'])
index=obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [195]:
index[1:]

Index(['b', 'c'], dtype='object')

In [196]:
#indexオブジェクトは変更不可能
index[1]='d'

TypeError: Index does not support mutable operations

In [70]:
labels=pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [71]:
obj2=pd.Series([1.5,-2.5,0],index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [74]:
obj2.index is labels

True

In [75]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [76]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [78]:
'Ohio' in frame3.columns

True

In [79]:
2003 in frame3.index

False

In [81]:
#pythonのセットとは異なり、pandasのインデックスは重複したラベルを持つことができる
dup_labels=pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [88]:
data=pd.DataFrame(np.arange(9).reshape(3,3),index=['one','foo','three'],columns=['foo','foo','bar'])
data

foo  foo  bar
one      0    1    2
foo      3    4    5
three    6    7    8

In [89]:
data['foo']

foo  foo
one      0    1
foo      3    4
three    6    7

In [90]:
data.T

one  foo  three
foo    0    3      6
foo    1    4      7
bar    2    5      8

In [91]:
data.T['foo']

foo    3
foo    4
bar    5
Name: foo, dtype: int64

## 5.2 pandasの重要な機能

### 5.2.1 再インデックス付け

In [92]:
obj=pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [93]:
#reindexメソッドを使うと新しいインデックスに従ってデータが再調整される
obj2=obj.reindex(['a','b','c','d','e']) #インデックスに対する既存の値がないと欠損値が代入される
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [94]:
obj3=pd.Series(['blue','purple','yellow'],index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [97]:
obj3.reindex(range(6),method='ffill')   #値を前方に穴埋めする

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [98]:
obj3    #reindexでは元のデータは変更されない

0      blue
2    purple
4    yellow
dtype: object

In [99]:
frame=pd.DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns=['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [100]:
frame2=frame.reindex(index=['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [101]:
states=['Texas','Utah','California']
frame.reindex(columns=states)   #引数columnを指定することで再インデックス付けすることができる

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [280]:
#locフィールドを使ったインデックス参照でも再インデックス付けができたがサポートされなくなった
#代替手段としてreindexが推奨されている
frame.loc[['a','b','c','d'],states]

KeyError: "None of [Index(['a', 'b', 'c', 'd'], dtype='object')] are in the [index]"

### 5.2.2 軸から要素を削除する

In [104]:
obj=pd.Series(np.arange(5.),index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [105]:
new_obj=obj.drop('c')   #指定した要素を軸から削除する
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [107]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [126]:
data=pd.DataFrame(np.arange(16).reshape(4,4),
                  index=['Ohio','Colorado','Utah','New York'],
                  columns=['one','two','three','four'])

data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [127]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [128]:
data.drop('two',axis=1) #列（axis=1）の'two'を消す

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [129]:
data.drop(['two','four'],axis='columns')    #columns=列

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [10]:
obj=pd.Series(np.arange(5.),index=['a','b','c','d','e'])
obj.drop('c',inplace=True)  #インプレースで直接置き換えることができる（削除したデータは完全になくなるので注意）
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### 5.2.3 インデックス参照、選択、フィルタリング

In [271]:
obj=pd.Series(np.arange(4.),index=['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [257]:
obj['b']

1.0

In [258]:
obj[1]

1.0

In [259]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [261]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [262]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [263]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [264]:
obj['b':'c']    #ラベルを使ったスライシングはPythonのスライシングと異なり、終点が含まれる

b    1.0
c    2.0
dtype: float64

In [272]:
obj[:2] #インデックスを使ったスライシングにはPythonのスライシングと同じく、終点は含まれない

a    0.0
b    1.0
dtype: float64

In [266]:
obj['b':'c']=5  #インデックス参照して取り出した部分に対して代入できる
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [273]:
data=pd.DataFrame(np.arange(16).reshape(4,4),
                  index=['Ohio','Colorado','Utah','New York'],
                  columns=['one','two','three','four'])

data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [268]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [269]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [274]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [275]:
data[data['three']>5]   #'three'の列が5より大きいデータを表示

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [276]:
data<5  #スカラー値と比較して真偽値を持つデータフレームを取得できる

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [278]:
data[data<5]=0  #5より小さいデータのみTrueになり、Trueの箇所全てに０を代入
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### 5.2.3.1 locとilocによるデータの選択
* locフィールドを使うとNumpyのように軸を指定して、データフレームから行や列の一部を選択することができる
* 軸のラベルを使うときはloc、整数のインデックス位置による参照を使うときはilocを使う

In [282]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [279]:
data.loc['Colorado',['two','three']]    #一つの行と複数の列を選択

two      5
three    6
Name: Colorado, dtype: int64

In [281]:
data.iloc[2,[3,0,1]]    #index=２のcolumns=3,0,1を表示

four    11
one      8
two      9
Name: Utah, dtype: int64

In [283]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [285]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [286]:
data.loc[:'Utah','two'] #ラベルによるスライシングが使える

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [287]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [289]:
data.iloc[:,:3]

one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

### 5.2.4 整数のインデックス

In [293]:
ser=pd.Series(np.arange(3.))
ser
ser[-1] #エラーになる

KeyError: -1

In [294]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [295]:
ser2=pd.Series(np.arange(3.),index=['a','b','c'])   #整数ではないインデックスを使う場合は問題ない
ser2[-1]

2.0

In [296]:
ser[:1] #インデックスとしての指定（index=0まで）

0    0.0
dtype: float64

In [297]:
ser.loc[:1] #ラベルとしての指定（ラベル1まで）

0    0.0
1    1.0
dtype: float64

In [298]:
ser.iloc[:1]    #インデックスとしての指定（index=0まで）

0    0.0
dtype: float64

### 5.2.5 算術とデータの整形

In [299]:
s1=pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])
s2=pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])

In [300]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [301]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [302]:
s1+s2   #加算結果のオブジェクトのインデックスは、加算前のインデックスのペアの和集合になる
#重複していないインデックスでは欠損値が代入される

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [303]:
df1=pd.DataFrame(np.arange(9.).reshape(3,3),columns=list('bcd'),index=['Ohio','Texas','Colorado'])
df2=pd.DataFrame(np.arange(12.).reshape(4,3),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [304]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [305]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [306]:
df1+df2 #データフレームではインデックスと列がそれぞれのデータフレームの和集合になる
#両方のデータフレームに存在しないインデックス、列の値はすべて欠損値になる

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [307]:
df1=pd.DataFrame({'A':[1,2]})
df2=pd.DataFrame({'B':[3,4]})

In [308]:
df1

A
0  1
1  2

In [309]:
df2

B
0  3
1  4

In [311]:
df1-df2 #ラベルが一つも共通しないデータフレームオブジェクトを加算した場合は結果はすべて欠損値になる

A   B
0 NaN NaN
1 NaN NaN

#### 5.2.5.1 算術メソッドと値の置換

In [323]:
df1=pd.DataFrame(np.arange(12.).reshape(3,4),columns=list('abcd'))
df2=pd.DataFrame(np.arange(20.).reshape(4,5),columns=list('abcde'))
df2.loc[1,'b']=np.nan

In [324]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [325]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [326]:
df1+df2 #軸ラベルが重複しないところはNaNになる

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [327]:
df1.add(df2,fill_value=0)   #軸ラベルが共通していない箇所が欠損値にならずに、各データフレームの値にfill_valueを加えた値が代入される

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [333]:
df1.add(df2,fill_value=100)

a      b      c      d      e
0    0.0    2.0    4.0    6.0  104.0
1    9.0  105.0   13.0   15.0  109.0
2   18.0   20.0   22.0   24.0  114.0
3  115.0  116.0  117.0  118.0  119.0

In [334]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [335]:
df1.rdiv(1) #rで始まるメソッドはオブジェクトと引数の関係が反転したもの

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [336]:
df1.reindex(columns=df2.columns,fill_value=0)   #再インデックス付けのときも同様に、置換する値を指定できる

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

#### 5.2.5.2 データフレームとシリーズでの演算

In [337]:
arr=np.arange(12.).reshape(3,4)
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [338]:
arr[0]

array([0., 1., 2., 3.])

In [339]:
arr-arr[0]  #ブロードキャストですべての行に対して演算が行われる

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [340]:
frame=pd.DataFrame(np.arange(12.).reshape(4,3),
                   columns=list('bde'),
                   index=['Utah','Ohio','Texas','Oregon'])
series=frame.iloc[0]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [341]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [342]:
# デフォルトでは、データフレームとシリーズの算術においては、
# シリーズのインデックスとデータフレームのオブジェクトの列がマッチングされ、ブロードキャストは行方向に行われる
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [343]:
series2=pd.Series(range(3),index=list('bef'))
series2

b    0
e    1
f    2
dtype: int64

In [344]:
# インデックスの値がデータフレームの列やシリーズのインデックスに見つからなかった場合は、
# 両方のオブジェクトは再インデックス付けされ、インデックスの和集合が形成される
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [345]:
series3=frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [346]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [347]:
# インデックスを行にマッチングさせて、列方向にブロードキャストを行う場合は
# 算術用のメソッドを使う必要がある
frame.sub(series3,axis='index') #指定した軸の値はインデックスをマッチさせたい軸を示す

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### 5.2.6 関数の適用とマッピング

In [348]:
frame=pd.DataFrame(np.random.randn(4,3),columns=list('bde'),
                   index=['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah   -0.043487  0.016152  1.267330
Ohio   -0.961627  0.790156 -0.938744
Texas  -2.377960 -0.327983 -1.235539
Oregon  2.595382  2.054314  0.784988

In [349]:
np.abs(frame)   #Numpyのufuncが適用できる

b         d         e
Utah    0.043487  0.016152  1.267330
Ohio    0.961627  0.790156  0.938744
Texas   2.377960  0.327983  1.235539
Oregon  2.595382  2.054314  0.784988

In [354]:
f=lambda x:x.max()-x.min()
frame.apply(f)  #１次元配列に適用可能な関数を行や列に対して適用する

b    4.973342
d    2.382297
e    2.502869
dtype: float64

In [355]:
frame.apply(f,axis='columns')   #各行に対して一度づつ関数が呼ばれる

Utah      1.310818
Ohio      1.751783
Texas     2.049977
Oregon    1.810395
dtype: float64

In [358]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])

frame.apply(f)  #複数の値を持ったシリーズをapplyに渡すことができる

b         d         e
min -2.377960 -0.327983 -1.235539
max  2.595382  2.054314  1.267330

In [359]:
#各小数値から書式化された文字列を計算する
format=lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah    -0.04   0.02   1.27
Ohio    -0.96   0.79  -0.94
Texas   -2.38  -0.33  -1.24
Oregon   2.60   2.05   0.78

In [360]:
frame['e'].map(format)

Utah       1.27
Ohio      -0.94
Texas     -1.24
Oregon     0.78
Name: e, dtype: object

### 5.2.7 ソートとランク

In [361]:
obj=pd.Series(range(4),index=list('dabc'))
obj

d    0
a    1
b    2
c    3
dtype: int64

In [362]:
obj.sort_index()    #新しいソート済みのオブジェクトを返す

a    1
b    2
c    3
d    0
dtype: int64

In [363]:
frame=pd.DataFrame(np.arange(8).reshape(2,4),
                   index=['three','one'],
                   columns=list('dabc'))
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [364]:
frame.sort_index()  #行をソート

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [365]:
frame.sort_index(axis=1)    #列をソート

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [366]:
frame.sort_index(axis=1,ascending=False)    #列を降順にソート

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [368]:
obj=pd.Series([4,7,-3,2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [369]:
obj.sort_values()   #値によってソート

2   -3
3    2
0    4
1    7
dtype: int64

In [370]:
obj=pd.Series([4,np.nan,7,np.nan,-3,2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [371]:
obj.sort_values()   #デフォルトでは欠損値はシリーズの末尾にソートされる

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [372]:
frame=pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [374]:
frame.sort_values(by='b')   #データフレームをソートする場合は一つ以上の列を指定する

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [375]:
frame.sort_values(by=['a','b']) #複数の列でソートする場合は列の名前をリストで渡す

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [392]:
obj=pd.Series([7,-5,7,2,4,0,4])
obj

0    7
1   -5
2    7
3    2
4    4
5    0
6    4
dtype: int64

In [393]:
# 配列のデータから妥当な数値をランクとして代入する
# デフォルトではタイになったグループは各グループに平均値を代入してランクを決める
obj.rank()  #rank4とrank5がともに値が4でタイなので(4+5)/2=4.5がランクになる

0    6.5
1    1.0
2    6.5
3    3.0
4    4.5
5    2.0
6    4.5
dtype: float64

In [394]:
obj.rank(method='first')    #観測された順番に従ってランク付け

0    6.0
1    1.0
2    7.0
3    3.0
4    4.0
5    2.0
6    5.0
dtype: float64

In [399]:
obj

0    7
1   -5
2    7
3    2
4    4
5    0
6    4
dtype: int64

In [397]:
#タイの値に対して、そのグループでの最大のランクを代入
obj.rank(method='max')  #rank4とrank5がタイなので大きい方のrank5が代入される

0    7.0
1    1.0
2    7.0
3    3.0
4    5.0
5    2.0
6    5.0
dtype: float64

In [400]:
obj.rank(ascending=False)   #降順でランク付け

0    1.5
1    7.0
2    1.5
3    5.0
4    3.5
5    6.0
6    3.5
dtype: float64

In [398]:
#タイの値に対して、そのグループでの最大のランクを降順で代入
obj.rank(ascending=False,method='max')  #rank1とrank2がタイなので大きい方のrank2が代入される

0    2.0
1    7.0
2    2.0
3    5.0
4    4.0
5    6.0
6    4.0
dtype: float64

In [198]:
frame=pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [199]:
#データフレームでは行か列でランク付けできる
frame.rank(axis='columns')  #列方向にランク付け

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### 5.2.8 重複したラベルを持つ軸のインデックス

In [200]:
obj=pd.Series(range(5),index=list('aabbc'))
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [201]:
obj.index.is_unique #インデックスのラベルが一意（重複がない）でないか確認する. Trueで重複なし

False

In [202]:
obj['a']    #重複がある場合はシリーズが返される

a    0
a    1
dtype: int64

In [203]:
obj['c']    #重複がない場合はスカラーが返される

4

In [206]:
df=pd.DataFrame(np.random.randn(4,3),index=list('aabc'))
df

0         1         2
a -1.030765 -0.200377  1.307668
a  0.491384  1.314265  2.092799
b  0.997562 -0.356474  0.804363
c  0.740953 -0.673532 -0.351153

In [207]:
df.loc['a'] #データフレームではインデックスに重複がある場合はデータフレームが返される

0         1         2
a -1.030765 -0.200377  1.307668
a  0.491384  1.314265  2.092799

In [208]:
df.loc['c'] #データフレームではインデックスに重複がない場合はシリーズが返される

0    0.740953
1   -0.673532
2   -0.351153
Name: c, dtype: float64

## 5.3 要約統計量の集計と計算

In [210]:
df=pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],
                index=list('abcd'),columns=['one','two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [211]:
df.sum()    #行方向に足して要素の合計値を返す（NaNは計算から除外される）

one    9.25
two   -5.80
dtype: float64

In [212]:
df.sum(axis='columns')  #列方向に足して要素の合計値を返す（NaNは計算から除外される）

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [213]:
df.sum(axis='columns',skipna=False) #NaNの計算除外を無効にする（NaNに対して何を計算してもNaNが返される）

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [214]:
df.idxmax() #最大の値を持つ場所を示すラベルを示す

one    b
two    d
dtype: object

In [215]:
df.cumsum() #累積和を返す

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [216]:
df.describe()   #複数の要約統計量を一回で返す（数値データ）

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [218]:
obj=pd.Series(list('aabc')*4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [219]:
obj.describe()  #複数の要約統計量を一回で返す（文字列データ）

count     16
unique     3
top        a
freq       8
dtype: object

### 5.3.1 相関と共分散

In [223]:
import pandas_datareader.data as web
all_data={ticker:web.get_data_yahoo(ticker) for ticker in ['AAPL','IBM','MSFT','GOOG']}
price=pd.DataFrame({ticker:data['Adj Close'] for ticker,data in  all_data.items()})
volume=pd.DataFrame({ticker:data['Volume'] for ticker,data in all_data.items()})

In [226]:
returns=price.pct_change() #株価のパーセント変化を求める
returns.tail()  #データの末尾５件を表示

AAPL       IBM      MSFT      GOOG
Date                                              
2021-02-09 -0.006574  0.000984  0.005362 -0.004491
2021-02-10 -0.004558  0.001147 -0.003897  0.005697
2021-02-11 -0.001920 -0.010880  0.006878  0.000243
2021-02-12  0.001776 -0.000910  0.002045  0.003922
2021-02-16 -0.016104 -0.006043 -0.005266  0.008455

In [227]:
returns['MSFT'].corr(returns['IBM'])    #二つのシリーズのインデックス順に並んだNAでない値の重なりから相関（correlation）を求める

0.5430931687617507

In [228]:
returns['MSFT'].cov(returns['IBM']) #二つのシリーズのインデックス順に並んだNAでない値の重なりから共分散（covariance）を求める

0.00015376153704527428

In [230]:
#簡潔な記法（MSFTがPythonオブジェクトの属性として有効になっている）
returns.MSFT.corr(returns.IBM)

0.5430931687617507

In [231]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.458603  0.709162  0.649545
IBM   0.458603  1.000000  0.543093  0.510684
MSFT  0.709162  0.543093  1.000000  0.777523
GOOG  0.649545  0.510684  0.777523  1.000000

In [232]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000357  0.000142  0.000232  0.000205
IBM   0.000142  0.000267  0.000154  0.000139
MSFT  0.000232  0.000154  0.000300  0.000225
GOOG  0.000205  0.000139  0.000225  0.000278

In [233]:
returns.corrwith(returns.IBM)   #データフレームの特定の行や列と、別のシリーズやデータフレームに対する相関を求めることができる

AAPL    0.458603
IBM     1.000000
MSFT    0.543093
GOOG    0.510684
dtype: float64

In [234]:
returns.corrwith(volume)    #パーセント表示と出来高との相関. 引数にデータフレームを渡すと一致した列名同士で相関が計算される

AAPL   -0.071209
IBM    -0.115281
MSFT   -0.087333
GOOG   -0.136797
dtype: float64

### 5.3.2 一意な値、頻度の確認、所属の確認

In [236]:
obj=pd.Series(list('cadaabbcc'))
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [238]:
uniques=obj.unique()    #シリーズの中の一意な値を取り出す（ソートはされない）
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [239]:
obj.value_counts()  #シリーズに含まれる値の頻度を求める

c    3
a    3
b    2
d    1
dtype: int64

In [241]:
pd.value_counts(obj.values,sort=True)   #value_countsはpandasのトップレベルのメソッドとしても使える

c    3
a    3
b    2
d    1
dtype: int64

In [242]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [243]:
mask=obj.isin(['b','c'])    #isinメソッドはベクトル形式の集合を指定して、その値のいずれかが含まれるかを確認できる. 部分集合を作るときに便利
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [244]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [245]:
to_match=pd.Series(list('cabbca'))
to_match

0    c
1    a
2    b
3    b
4    c
5    a
dtype: object

In [246]:
unique_vals=pd.Series(list('cba'))
unique_vals

0    c
1    b
2    a
dtype: object

In [247]:
pd.Index(unique_vals).get_indexer(to_match) #一意でないかもしれない配列を一意な配列にするためのインデックス配列を返す

array([0, 2, 1, 1, 0, 2])

In [248]:
data=pd.DataFrame({'Qu1':[1,3,4,3,4],
                   'Qu2':[2,3,1,2,3],
                   'Qu3':[1,5,2,4,4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [251]:
result=data.apply(pd.value_counts)    #value_countsメソッドをapplyメソッドに適用する
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  NaN  2.0  1.0
3  2.0  2.0  NaN
4  2.0  NaN  2.0
5  NaN  NaN  1.0

In [252]:
result=data.apply(pd.value_counts).fillna(0)    #value_countsメソッドをapplyメソッドに適用する.fillna(0)で欠損値を0で埋める
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0